// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'get_test.dart' as get_test;
import 'patch_test.dart' as patch_test;
import 'post_test.dart' as post_test;
import 'put_test.dart' as put_test;

void main() {
  get_test.main();
  patch_test.main();
  post_test.main();
  put_test.main();
}
