name: fanoos_http
description: A concise and robust Http client for Dart with no need for code generation or reflection.
version: 1.0.0
homepage: https://github.com/ali2236/fanoos_http

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
